### ISSUE TITLE
Combination Of Text and Image in Text View

### ISSUE THREAD

**Issue by DumbestWalls** [DumbestWalls/MeowPanda#1]
![Screenshot 2021-08-17 at 4 28 38 PM](https://user-images.githubusercontent.com/88792486/129714648-30311291-711a-4de9-9dbf-4e7c969609ee.png)

I want to Add Facebook logo & Google Logo to the Left of their Text Facebook & Google in their Text View respectively.

For that:

### **selected View >> attribute : drawableLeft >> Choose Image.**

**But the Result is:**

![Screenshot 2021-08-17 at 4 33 34 PM](https://user-images.githubusercontent.com/88792486/129715255-4754bdac-bb7b-40f6-b826-4b79f9695711.png)

**Result Required is:**

![Screenshot 2021-08-17 at 4 37 07 PM](https://user-images.githubusercontent.com/88792486/129715693-ed806a75-c5d2-4753-8f56-9ee146bf92f0.png)

**Comment by vmaffioli** [comment]
Greetings, 
I want to solve this issue.

**Comment by vmaffioli** [comment]
To add an image to textview I've used the android props "drawableLeft" to draw the choosen png from res/drawables, to resize the image element I've create two new image files called "facebookSmall" and "googleSmall" representing the resized icons.
Pull Request : https://github.com/DumbestWalls/MeowPanda/pull/2

**Comment by DumbestWalls** [comment]
Thanks For solving. 
Basically, All I had to do was to Resize the Logo. Right?

**Comment by vmaffioli** [comment]
Yes friend, I saw other ways to resize the img in code, but using a textview like used in project I could not apply size props. Talking about xml, you could build a custom element for this, but resizing the source is a quick solution.

**Comment by DumbestWalls** [comment]
Ok I got it. 
Thank you.

**Comment by vmaffioli** [comment]
Could you assign me to this issue please?
